# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Versido Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Versido Blog shares story about Design and Web Development.
baseurl: "/blog/" # the subpath of your site, e.g. /blog
url: "https://versido.my.id" # the base hostname & protocol for your site
twitter_username: versido
github_username:  versido

# Build settings
markdown: kramdown
